// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proto/tunnel/v1/tunnel.proto

package tunnelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameType int32

const (
	FrameType_FRAME_TYPE_UNSPECIFIED   FrameType = 0
	FrameType_FRAME_TYPE_REGISTER      FrameType = 1
	FrameType_FRAME_TYPE_REGISTERED    FrameType = 2
	FrameType_FRAME_TYPE_REQUEST_HEAD  FrameType = 3
	FrameType_FRAME_TYPE_RESPONSE_HEAD FrameType = 4
	FrameType_FRAME_TYPE_DATA          FrameType = 5
	FrameType_FRAME_TYPE_END           FrameType = 6
	FrameType_FRAME_TYPE_CANCEL        FrameType = 7
	FrameType_FRAME_TYPE_PING          FrameType = 8
	FrameType_FRAME_TYPE_PONG          FrameType = 9
	FrameType_FRAME_TYPE_ERROR         FrameType = 10
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0:  "FRAME_TYPE_UNSPECIFIED",
		1:  "FRAME_TYPE_REGISTER",
		2:  "FRAME_TYPE_REGISTERED",
		3:  "FRAME_TYPE_REQUEST_HEAD",
		4:  "FRAME_TYPE_RESPONSE_HEAD",
		5:  "FRAME_TYPE_DATA",
		6:  "FRAME_TYPE_END",
		7:  "FRAME_TYPE_CANCEL",
		8:  "FRAME_TYPE_PING",
		9:  "FRAME_TYPE_PONG",
		10: "FRAME_TYPE_ERROR",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED":   0,
		"FRAME_TYPE_REGISTER":      1,
		"FRAME_TYPE_REGISTERED":    2,
		"FRAME_TYPE_REQUEST_HEAD":  3,
		"FRAME_TYPE_RESPONSE_HEAD": 4,
		"FRAME_TYPE_DATA":          5,
		"FRAME_TYPE_END":           6,
		"FRAME_TYPE_CANCEL":        7,
		"FRAME_TYPE_PING":          8,
		"FRAME_TYPE_PONG":          9,
		"FRAME_TYPE_ERROR":         10,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_v1_tunnel_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_proto_tunnel_v1_tunnel_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_tunnel_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Engine        string                 `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_proto_tunnel_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *Register) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *Register) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Register) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *Register) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RequestHead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	RawQuery      string                 `protobuf:"bytes,3,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	Headers       []*Header              `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHead) Reset() {
	*x = RequestHead{}
	mi := &file_proto_tunnel_v1_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHead) ProtoMessage() {}

func (x *RequestHead) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_v1_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHead.ProtoReflect.Descriptor instead.
func (*RequestHead) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *RequestHead) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestHead) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestHead) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *RequestHead) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ResponseHead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers       []*Header              `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHead) Reset() {
	*x = ResponseHead{}
	mi := &file_proto_tunnel_v1_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHead) ProtoMessage() {}

func (x *ResponseHead) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_v1_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHead.ProtoReflect.Descriptor instead.
func (*ResponseHead) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseHead) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ResponseHead) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Envelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	StreamId        string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Type            FrameType              `protobuf:"varint,3,opt,name=type,proto3,enum=modeluplink.tunnel.v1.FrameType" json:"type,omitempty"`
	Register        *Register              `protobuf:"bytes,4,opt,name=register,proto3" json:"register,omitempty"`
	RequestHead     *RequestHead           `protobuf:"bytes,5,opt,name=request_head,json=requestHead,proto3" json:"request_head,omitempty"`
	ResponseHead    *ResponseHead          `protobuf:"bytes,6,opt,name=response_head,json=responseHead,proto3" json:"response_head,omitempty"`
	Data            []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Error           string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_tunnel_v1_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_v1_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *Envelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Envelope) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Envelope) GetType() FrameType {
	if x != nil {
		return x.Type
	}
	return FrameType_FRAME_TYPE_UNSPECIFIED
}

func (x *Envelope) GetRegister() *Register {
	if x != nil {
		return x.Register
	}
	return nil
}

func (x *Envelope) GetRequestHead() *RequestHead {
	if x != nil {
		return x.RequestHead
	}
	return nil
}

func (x *Envelope) GetResponseHead() *ResponseHead {
	if x != nil {
		return x.ResponseHead
	}
	return nil
}

func (x *Envelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Envelope) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_tunnel_v1_tunnel_proto protoreflect.FileDescriptor

const file_proto_tunnel_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/tunnel/v1/tunnel.proto\x12\x15modeluplink.tunnel.v1\"4\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\xad\x01\n" +
	"\bRegister\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"\x8f\x01\n" +
	"\vRequestHead\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1b\n" +
	"\traw_query\x18\x03 \x01(\tR\brawQuery\x127\n" +
	"\aheaders\x18\x04 \x03(\v2\x1d.modeluplink.tunnel.v1.HeaderR\aheaders\"_\n" +
	"\fResponseHead\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x127\n" +
	"\aheaders\x18\x02 \x03(\v2\x1d.modeluplink.tunnel.v1.HeaderR\aheaders\"\x80\x03\n" +
	"\bEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x124\n" +
	"\x04type\x18\x03 \x01(\x0e2 .modeluplink.tunnel.v1.FrameTypeR\x04type\x12;\n" +
	"\bregister\x18\x04 \x01(\v2\x1f.modeluplink.tunnel.v1.RegisterR\bregister\x12E\n" +
	"\frequest_head\x18\x05 \x01(\v2\".modeluplink.tunnel.v1.RequestHeadR\vrequestHead\x12H\n" +
	"\rresponse_head\x18\x06 \x01(\v2#.modeluplink.tunnel.v1.ResponseHeadR\fresponseHead\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error*\x96\x02\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FRAME_TYPE_REGISTER\x10\x01\x12\x19\n" +
	"\x15FRAME_TYPE_REGISTERED\x10\x02\x12\x1b\n" +
	"\x17FRAME_TYPE_REQUEST_HEAD\x10\x03\x12\x1c\n" +
	"\x18FRAME_TYPE_RESPONSE_HEAD\x10\x04\x12\x13\n" +
	"\x0fFRAME_TYPE_DATA\x10\x05\x12\x12\n" +
	"\x0eFRAME_TYPE_END\x10\x06\x12\x15\n" +
	"\x11FRAME_TYPE_CANCEL\x10\a\x12\x13\n" +
	"\x0fFRAME_TYPE_PING\x10\b\x12\x13\n" +
	"\x0fFRAME_TYPE_PONG\x10\t\x12\x14\n" +
	"\x10FRAME_TYPE_ERROR\x10\n" +
	"BJZHgithub.com/oscar-investmatic/modeluplink-client/proto/tunnel/v1;tunnelv1b\x06proto3"

var (
	file_proto_tunnel_v1_tunnel_proto_rawDescOnce sync.Once
	file_proto_tunnel_v1_tunnel_proto_rawDescData []byte
)

func file_proto_tunnel_v1_tunnel_proto_rawDescGZIP() []byte {
	file_proto_tunnel_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_tunnel_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tunnel_v1_tunnel_proto_rawDesc), len(file_proto_tunnel_v1_tunnel_proto_rawDesc)))
	})
	return file_proto_tunnel_v1_tunnel_proto_rawDescData
}

var file_proto_tunnel_v1_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_tunnel_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tunnel_v1_tunnel_proto_goTypes = []any{
	(FrameType)(0),       // 0: modeluplink.tunnel.v1.FrameType
	(*Header)(nil),       // 1: modeluplink.tunnel.v1.Header
	(*Register)(nil),     // 2: modeluplink.tunnel.v1.Register
	(*RequestHead)(nil),  // 3: modeluplink.tunnel.v1.RequestHead
	(*ResponseHead)(nil), // 4: modeluplink.tunnel.v1.ResponseHead
	(*Envelope)(nil),     // 5: modeluplink.tunnel.v1.Envelope
}
var file_proto_tunnel_v1_tunnel_proto_depIdxs = []int32{
	1, // 0: modeluplink.tunnel.v1.RequestHead.headers:type_name -> modeluplink.tunnel.v1.Header
	1, // 1: modeluplink.tunnel.v1.ResponseHead.headers:type_name -> modeluplink.tunnel.v1.Header
	0, // 2: modeluplink.tunnel.v1.Envelope.type:type_name -> modeluplink.tunnel.v1.FrameType
	2, // 3: modeluplink.tunnel.v1.Envelope.register:type_name -> modeluplink.tunnel.v1.Register
	3, // 4: modeluplink.tunnel.v1.Envelope.request_head:type_name -> modeluplink.tunnel.v1.RequestHead
	4, // 5: modeluplink.tunnel.v1.Envelope.response_head:type_name -> modeluplink.tunnel.v1.ResponseHead
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_tunnel_v1_tunnel_proto_init() }
func file_proto_tunnel_v1_tunnel_proto_init() {
	if File_proto_tunnel_v1_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tunnel_v1_tunnel_proto_rawDesc), len(file_proto_tunnel_v1_tunnel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tunnel_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_tunnel_v1_tunnel_proto_depIdxs,
		EnumInfos:         file_proto_tunnel_v1_tunnel_proto_enumTypes,
		MessageInfos:      file_proto_tunnel_v1_tunnel_proto_msgTypes,
	}.Build()
	File_proto_tunnel_v1_tunnel_proto = out.File
	file_proto_tunnel_v1_tunnel_proto_goTypes = nil
	file_proto_tunnel_v1_tunnel_proto_depIdxs = nil
}
